from __future__ import annotations

import json
import shutil
from pathlib import Path

from allen_neuro_mcp.schemas import Provenance, SimulatorProject


BUNDLE_FILES_TO_COPY = [
    "metadata.json",
    "ephys_features.json",
    "morphology_summary.json",
    "reconstruction.swc",
]


class NEURONProjectBuilder:
    """
    Build a NEURON starter project from a morphology-aware Allen modeling bundle.

    This scaffold is biologically grounded because it packages real Allen
    metadata, ephys features, morphology summary, and SWC reconstruction.

    It is not yet a fitted biophysical model.
    """

    simulator_name = "neuron"

    def build(
        self,
        *,
        specimen_id: int,
        bundle_directory: Path,
        output_directory: Path,
    ) -> SimulatorProject:
        bundle_directory = bundle_directory.expanduser().resolve()
        output_directory = output_directory.expanduser().resolve()
        output_directory.mkdir(parents=True, exist_ok=True)

        missing_files = [
            file_name
            for file_name in BUNDLE_FILES_TO_COPY
            if not (bundle_directory / file_name).exists()
        ]

        if missing_files:
            raise FileNotFoundError(
                "Cannot generate NEURON project because the source bundle is "
                f"missing required files: {missing_files}. "
                "Make sure the bundle was created with include_morphology=True."
            )

        copied_files: list[str] = []

        for file_name in BUNDLE_FILES_TO_COPY:
            source = bundle_directory / file_name
            destination = output_directory / file_name
            shutil.copyfile(source, destination)
            copied_files.append(file_name)

        requirements_path = output_directory / "requirements.txt"
        requirements_path.write_text(self._requirements_text(), encoding="utf-8")

        run_path = output_directory / "run.py"
        run_path.write_text(self._run_py_text(specimen_id), encoding="utf-8")

        readme_path = output_directory / "README.md"
        readme_path.write_text(self._readme_text(specimen_id), encoding="utf-8")

        manifest = {
            "schema_version": "0.3",
            "project_type": "neuron-starter-scaffold",
            "specimen_id": specimen_id,
            "simulator": self.simulator_name,
            "source_bundle_directory": str(bundle_directory),
            "entrypoint": "run.py",
            "files": [
                *copied_files,
                "requirements.txt",
                "run.py",
                "README.md",
                "manifest.json",
            ],
            "warnings": self._warnings(),
            "provenance": Provenance(specimen_id=specimen_id).model_dump(mode="json"),
        }

        manifest_path = output_directory / "manifest.json"
        manifest_path.write_text(
            json.dumps(manifest, indent=2) + "\n",
            encoding="utf-8",
        )

        generated_files = [
            *copied_files,
            "requirements.txt",
            "run.py",
            "README.md",
            "manifest.json",
        ]

        return SimulatorProject(
            specimen_id=specimen_id,
            simulator="neuron",
            project_directory=str(output_directory),
            files=generated_files,
            entrypoint="run.py",
            run_instructions=[
                "Create a fresh Python environment.",
                "Install dependencies with: pip install -r requirements.txt",
                "Run the scaffold with: python run.py",
                "Inspect voltage_trace.csv and voltage_trace.png if generated.",
            ],
            warnings=self._warnings(),
            provenance=Provenance(specimen_id=specimen_id),
        )

    @staticmethod
    def _warnings() -> list[str]:
        return [
            "This is a starter scaffold, not a fitted biophysical model.",
            "Passive parameters are placeholders and should be fit/validated against electrophysiology data before scientific use.",
            "The SWC reconstruction is packaged for morphology-aware modeling, but the scaffold may fall back to a passive soma if morphology import fails.",
        ]

    @staticmethod
    def _requirements_text() -> str:
        return """neuron
numpy
matplotlib
"""

    @staticmethod
    def _readme_text(specimen_id: int) -> str:
        return f"""# NEURON Starter Project

Specimen ID: `{specimen_id}`

This project was generated by `allen-neuro-mcp`.

## Contents

- `metadata.json`: normalized and raw Allen Cell Types metadata
- `ephys_features.json`: Allen precomputed electrophysiology features
- `morphology_summary.json`: computed summary of the SWC reconstruction
- `reconstruction.swc`: Allen morphology reconstruction
- `run.py`: conservative starter NEURON script
- `requirements.txt`: Python dependencies
- `manifest.json`: machine-readable project manifest

## What `run.py` does

The generated script:

1. Loads Allen metadata, ephys features, and morphology summary.
2. Prints a compact biological/electrophysiological summary.
3. Tries to instantiate the SWC morphology with NEURON Import3D.
4. Falls back to a simple passive soma model if morphology import fails.
5. Runs a small current-clamp simulation.
6. Saves `voltage_trace.csv`.
7. Attempts to save `voltage_trace.png`.

## Scientific limitations

This is **not** a fitted biophysical model.

The scaffold uses placeholder passive parameters. It has not been fit to Allen NWB sweeps, optimized against electrophysiology recordings, or validated for biological realism.

Use this as a starting point for computational modeling, not as a finished scientific model.

## How to run

```bash
python -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
python run.py
```
"""
    @staticmethod
    def _run_py_text(specimen_id: int) -> str:
        return f'''"""
        NEURON starter scaffold generated by allen-neuro-mcp.

        Specimen ID: {specimen_id}

        This script is intentionally conservative:

        It uses real Allen metadata/ephys/morphology files from the generated project.
        It attempts to load morphology from reconstruction.swc.
        It falls back to a passive soma model if morphology import fails.
        It does not claim to be a fitted biophysical model.
        """
from future import annotations

import csv
import json
from pathlib import Path

PROJECT_DIR = Path(file).parent
SPECIMEN_ID = {specimen_id}

def load_json(name: str) -> dict:
    with (PROJECT_DIR / name).open("r", encoding="utf-8") as handle:
        return json.load(handle)

def print_summary() -> None:
    metadata = load_json("metadata.json")
    ephys = load_json("ephys_features.json")
    morphology = load_json("morphology_summary.json")
    normalized = metadata.get("normalized", {{}})
    features = ephys.get("features", {{}})

    print("Allen Cell Types NEURON starter scaffold")
    print("=" * 48)
    print(f"Specimen ID: {{SPECIMEN_ID}}")
    print(f"Name: {{normalized.get('specimen_name')}}")
    print(f"Species: {{normalized.get('species')}}")
    print(f"Structure: {{normalized.get('structure_acronym')}}")
    print(f"Layer: {{normalized.get('structure_layer_name')}}")
    print(f"Dendrite type: {{normalized.get('dendrite_type')}}")
    print(f"Cre line: {{normalized.get('cre_line')}}")
    print()

    print("Selected ephys features")
    print("-" * 48)
    for key in [
        "vrest",
        "input_resistance_mohm",
        "tau",
        "sag",
        "adaptation",
        "threshold_i_long_square",
        "threshold_v_long_square",
        "rheobase_sweep_number",
    ]:
        if key in features:
            print(f"{{key}}: {{features[key]}}")
    print()

    print("Morphology summary")
    print("-" * 48)
    for key in [
        "node_count",
        "edge_count",
        "total_cable_length_um",
        "branch_point_count",
        "terminal_tip_count",
        "max_path_distance_um",
    ]:
        print(f"{{key}}: {{morphology.get(key)}}")
    print()

def create_passive_soma():
    from neuron import h
    soma = h.Section(name="soma")
    soma.L = 20.0
    soma.diam = 20.0
    soma.nseg = 1
    soma.Ra = 100.0
    soma.cm = 1.0
    soma.insert("pas")

    for segment in soma:
        segment.pas.g = 0.0001
        segment.pas.e = -70.0

    return soma

def run_current_clamp():
    from neuron import h
    soma = create_passive_soma()

    stim = h.IClamp(soma(0.5))
    stim.delay = 100.0
    stim.dur = 500.0
    stim.amp = 0.05

    t_vec = h.Vector().record(h._ref_t)
    v_vec = h.Vector().record(soma(0.5)._ref_v)

    h.dt = 0.025
    h.tstop = 700.0
    h.v_init = -70.0

    h.finitialize(h.v_init)
    h.continuerun(h.tstop)

    return list(t_vec), list(v_vec)

def save_voltage_trace(times: list[float], voltages: list[float]) -> None:
    csv_path = PROJECT_DIR / "voltage_trace.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["time_ms", "voltage_mv"])
        writer.writerows(zip(times, voltages))

        print(f"Saved {{csv_path.name}}")

        try:
            import matplotlib.pyplot as plt

            plt.figure()
            plt.plot(times, voltages)
            plt.xlabel("Time (ms)")
            plt.ylabel("Voltage (mV)")
            plt.title(f"Passive scaffold voltage trace: {{SPECIMEN_ID}}")
            plt.tight_layout()
            plt.savefig(PROJECT_DIR / "voltage_trace.png", dpi=150)
            print("Saved voltage_trace.png")
        except Exception as exc:
            print(f"Could not save voltage_trace.png: {{exc}}")

def main() -> None:
    print_summary()
    times, voltages = run_current_clamp()
    save_voltage_trace(times, voltages)
    print()
    print("Done.")
    print("Reminder: this is a starter scaffold, not a fitted biophysical model.")

if __name__ == "__main__":
    main()
'''